AllCops:
  DisabledByDefault: true
  inherit_mode:
    merge:
      - Include
  Include:
    - '**/*.cr'

Crystal/FileExtension:
  Description: 'This cop renames files ending in `.rb` to `.cr`.'
  Enabled: true

Crystal/InterpolationInSingleQuotes:
  Description: "This cop uses %q in place of ' if the enclosed string would be affected by interpolation."
  Enabled: true

Crystal/MethodNameStartingWithUppercaseLetter:
  Description: 'This cop detects method names that start with uppercase letters.'
  Enabled: true

Crystal/RequireRelative:
  Description: 'This cop replaces require_relative with require while maintaining behavior.'
  Enabled: true

Lint/ImplicitStringConcatenation:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WhileUntilDo:
  Enabled: true
