AllCops:
  DisabledByDefault: true

Crystal/FileExtension:
  Description: 'This cop renames files ending in `.rb` to `.cr`.'
  Enabled: true

Crystal/InterpolationInSingleQuotes:
  Description: "This cop uses %q in place of ' if the enclosed string would be affected by interpolation."
  Enabled: true

Crystal/RequireRelative:
  Description: 'This cop replaces require_relative with require while maintaining behavior.'
  Enabled: true

Lint/ImplicitStringConcatenation:
  Enabled: true

Style/BlockComments:
  Enforced: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/MethodDefParentheses:
  Enabled: true
